MODEL:
  NAME: IKEM
  IMAGE_SIZE: [3, 512, 256]
  NUM_KEYPOINTS: 68
  HintFusionLayer:
    ScaleLayer: True  # 在hintmap_encoder的最後縮放
    out_channel: 64  # 輸入HRNet的channel數
  IGGNet:
    BLOCK: 
    Conv_channels:
    kernels:

  HRNet:
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 2
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 2
      - 2
      NUM_CHANNELS:
      - 18
      - 36
    STAGE3:
      NUM_MODULES: 3
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 2
      - 2
      - 2
      NUM_CHANNELS:
      - 18
      - 36
      - 72
    STAGE4:
      NUM_MODULES: 2
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 2
      - 2
      - 2
      - 2
      NUM_CHANNELS:
      - 18
      - 36
      - 72
      - 144


Dataset:
  NAME: 'dataset16'
  image_size: [512, 256]
  num_keypoint: 68
  heatmap_std: 7.5
  aug:
    type: 'aug_default'
    p: [0.2, 0.2, 0.2, 0.2]
  subpixel_decoding_patch_size: 15
  subpixel_decoding: True


# CUDNN:
#   BENCHMARK: true
#   DETERMINISTIC: false
#   ENABLED: true
# DATASET:
#   DATASET: 'imagenet'
#   DATA_FORMAT: 'zip'
#   ROOT: 'data/imagenet/'
#   TEST_SET: 'val'
#   TRAIN_SET: 'train'
# TEST:
#   BATCH_SIZE_PER_GPU: 32
#   MODEL_FILE: ''
# TRAIN:
#   BATCH_SIZE_PER_GPU: 32
#   BEGIN_EPOCH: 0
#   END_EPOCH: 100
#   RESUME: true
#   LR_FACTOR: 0.1
#   LR_STEP:
#   - 30
#   - 60
#   - 90
#   OPTIMIZER: sgd
#   LR: 0.05
#   WD: 0.0001
#   MOMENTUM: 0.9
#   NESTEROV: true
#   SHUFFLE: true
# DEBUG:
#   DEBUG: false
